// flow-typed signature: a171bc1e90ff3002c00b5dc7c2d635f9
// flow-typed version: <<STUB>>/apollo-datasource-rest_v^0.8.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-datasource-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-datasource-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-datasource-rest/dist/HTTPCache' {
  declare module.exports: any;
}

declare module 'apollo-datasource-rest/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-datasource-rest/dist/RESTDataSource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-datasource-rest/dist/HTTPCache.js' {
  declare module.exports: $Exports<'apollo-datasource-rest/dist/HTTPCache'>;
}
declare module 'apollo-datasource-rest/dist/index.js' {
  declare module.exports: $Exports<'apollo-datasource-rest/dist/index'>;
}
declare module 'apollo-datasource-rest/dist/RESTDataSource.js' {
  declare module.exports: $Exports<'apollo-datasource-rest/dist/RESTDataSource'>;
}
